<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>BetterSubnautica</RootNamespace>
        <AssemblyName>BetterSubnautica</AssemblyName>
    </PropertyGroup>

    <PropertyGroup>
        <StartAction>Program</StartAction>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsSubnautica)' == 'true'">
        <StartProgram>$(GameDir)\Subnautica.exe</StartProgram>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsBelowZero)' == 'true'">
        <StartProgram>$(GameDir)\SubnauticaZero.exe</StartProgram>
    </PropertyGroup>

</Project>
